import { Resend } from "resend";
import type { Document, CaseFile, Profile } from "./types";
import { WIZARD_LABELS } from "./types";

let _resend: Resend | null = null;
function getResend(): Resend {
  if (!_resend) _resend = new Resend(process.env.RESEND_API_KEY!);
  return _resend;
}

const ATTORNEY_EMAIL = process.env.ATTORNEY_EMAIL ?? "andrew@crawfordlaw.net";
const FROM_EMAIL = "noreply@instant-attorney.com";

export async function notifyAttorneyDocumentReady(
  document: Document,
  caseFile: CaseFile,
  clientProfile: Profile
): Promise<void> {
  if (process.env.BYPASS_AUTH === "true" || !process.env.RESEND_API_KEY) {
    console.log(
      `[notify] BYPASS or no RESEND_API_KEY — skipping email for doc ${document.id}`
    );
    return;
  }

  const docLabel = WIZARD_LABELS[document.doc_type] ?? document.doc_type;
  const reviewUrl = `https://instant-attorney.com/attorney/review/${document.id}`;

  await getResend().emails.send({
    from: FROM_EMAIL,
    to: ATTORNEY_EMAIL,
    subject: `[Instant Attorney] ${docLabel} ready for review — ${clientProfile.full_name ?? clientProfile.email}`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
        <h2 style="color: #1a1a2e;">Document Ready for 48-Hour Review</h2>
        <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
          <tr>
            <td style="padding: 8px; font-weight: bold; width: 140px;">Client</td>
            <td style="padding: 8px;">${clientProfile.full_name ?? "—"} (${clientProfile.email})</td>
          </tr>
          <tr style="background: #f5f5f5;">
            <td style="padding: 8px; font-weight: bold;">Document Type</td>
            <td style="padding: 8px;">${docLabel}</td>
          </tr>
          <tr>
            <td style="padding: 8px; font-weight: bold;">Matter</td>
            <td style="padding: 8px;">${caseFile.matter_type ?? "Unknown"} — ${caseFile.matter_subtype ?? ""}</td>
          </tr>
          <tr style="background: #f5f5f5;">
            <td style="padding: 8px; font-weight: bold;">Case File ID</td>
            <td style="padding: 8px; font-size: 12px; color: #666;">${caseFile.id}</td>
          </tr>
        </table>
        <p style="margin: 24px 0;">
          <a href="${reviewUrl}" style="background: #1a1a2e; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">
            Review Document →
          </a>
        </p>
        <p style="font-size: 12px; color: #888; margin-top: 32px; border-top: 1px solid #eee; padding-top: 12px;">
          This document was generated by the Instant Attorney intake system. It is marked DRAFT and requires attorney review before delivery to the client.
          Crawford Law PLLC · Texas Bar #24148908
        </p>
      </div>
    `,
  });
}

export async function notifyClientDocumentApproved(
  document: Document,
  clientProfile: Profile
): Promise<void> {
  if (!process.env.RESEND_API_KEY) return;

  const docLabel = WIZARD_LABELS[document.doc_type] ?? document.doc_type;

  await getResend().emails.send({
    from: FROM_EMAIL,
    to: clientProfile.email,
    subject: `Your ${docLabel} is ready — Instant Attorney`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
        <h2 style="color: #1a1a2e;">Your Document Has Been Reviewed</h2>
        <p>Your <strong>${docLabel}</strong> has been reviewed and approved by Andrew Crawford, Esq. at Crawford Law PLLC.</p>
        <p style="margin: 24px 0;">
          <a href="https://instant-attorney.com/dashboard" style="background: #1a1a2e; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">
            View in Your File →
          </a>
        </p>
        <p style="font-size: 12px; color: #888; margin-top: 32px; border-top: 1px solid #eee; padding-top: 12px;">
          Crawford Law PLLC · Texas Bar #24148908 · This document is attorney-client privileged.
        </p>
      </div>
    `,
  });
}
