// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/next-step/Stage1TellStory.tsx": () => import("../components/mockups/next-step/Stage1TellStory.tsx"),
  "./components/mockups/next-step/Stage2CreateDoc.tsx": () => import("../components/mockups/next-step/Stage2CreateDoc.tsx"),
  "./components/mockups/next-step/Stage3ReviewDraft.tsx": () => import("../components/mockups/next-step/Stage3ReviewDraft.tsx"),
  "./components/mockups/next-step/Stage4UnderReview.tsx": () => import("../components/mockups/next-step/Stage4UnderReview.tsx"),
  "./components/mockups/next-step/Stage5Done.tsx": () => import("../components/mockups/next-step/Stage5Done.tsx"),
  "./components/mockups/next-step/StageNewDraftWhileSent.tsx": () => import("../components/mockups/next-step/StageNewDraftWhileSent.tsx"),
  "./components/mockups/next-step/StageRevisions.tsx": () => import("../components/mockups/next-step/StageRevisions.tsx")
};
