-- Durable policy/audit state for proactive generation. Generated content stays
-- in client_workspace_drafts; promotion remains the sole path to documents.
create table if not exists document_generation_jobs (
  id uuid default gen_random_uuid() primary key,
  case_file_id uuid references case_files(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  document_key text not null,
  document_type text not null,
  generation_revision bigint not null,
  status text not null check (status in ('queued','running','completed','cancelled','superseded','failed')),
  launch_reason text not null check (launch_reason in ('user_requested','package_confirmed','strategy_confirmed')),
  scheduling_priority integer not null check (scheduling_priority >= 0),
  plan_confidence text not null check (plan_confidence in ('low','medium','high')),
  required_fact_coverage numeric not null check (required_fact_coverage between 0 and 1),
  estimated_model_cost numeric not null check (estimated_model_cost >= 0),
  workspace_draft_id uuid references client_workspace_drafts(id) on delete set null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists document_generation_jobs_case_queue_idx
  on document_generation_jobs (case_file_id, status, scheduling_priority, created_at);

create table if not exists document_generation_outcomes (
  id bigint generated by default as identity primary key,
  case_file_id uuid references case_files(id) on delete cascade not null,
  document_type text not null,
  outcome text not null check (outcome in ('generated','opened','edited','promoted','cancelled','discarded')),
  job_id uuid references document_generation_jobs(id) on delete set null,
  occurred_at timestamptz default now() not null
);

create index if not exists document_generation_outcomes_type_idx
  on document_generation_outcomes (document_type, outcome, occurred_at desc);

-- Serialize admission per case and reject a fourth active job, including when
-- several schedulers race. Updating an already-active job does not count itself.
create or replace function enforce_document_generation_active_limit()
returns trigger language plpgsql as $$
begin
  if new.status in ('queued', 'running') then
    perform pg_advisory_xact_lock(hashtextextended(new.case_file_id::text, 0));
    if (select count(*) from document_generation_jobs
        where case_file_id = new.case_file_id
          and status in ('queued', 'running')
          and id <> new.id) >= 3 then
      raise exception 'per-case active document generation limit (3) reached';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists document_generation_active_limit on document_generation_jobs;
create trigger document_generation_active_limit
  before insert or update of status on document_generation_jobs
  for each row execute function enforce_document_generation_active_limit();

alter table document_generation_jobs enable row level security;
alter table document_generation_outcomes enable row level security;
-- No client policies: service-side scheduling and event endpoints own writes.
