-- Durable policy/audit state for proactive generation. Generated content stays
-- in client_workspace_drafts; promotion remains the sole path to documents.
-- document_generation_jobs is NOT created here. Stage 47 owns it, and that
-- definition is the one deployed. This file originally declared its own,
-- incompatible version — sharing only 7 columns and using a different status
-- vocabulary — which `create table if not exists` would have silently no-opped
-- against, leaving this policy writing to columns that never existed. Its index
-- on scheduling_priority went the same way: that column exists only in the
-- definition that lost, so the index would have failed outright.
--
-- The enforcement below now attaches to stage 47's table instead.

create table if not exists document_generation_outcomes (
  id bigint generated by default as identity primary key,
  case_file_id uuid references case_files(id) on delete cascade not null,
  document_type text not null,
  outcome text not null check (outcome in ('generated','opened','edited','promoted','cancelled','discarded')),
  job_id uuid references document_generation_jobs(id) on delete set null,
  occurred_at timestamptz default now() not null
);

create index if not exists document_generation_outcomes_type_idx
  on document_generation_outcomes (document_type, outcome, occurred_at desc);

-- Serialize admission per case and reject a fourth active job, including when
-- several schedulers race. Updating an already-active job does not count itself.
create or replace function enforce_document_generation_active_limit()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  -- Stage 47's active states. 'running' does not exist in its vocabulary, so
  -- the original check never fired and the cap silently allowed any number of
  -- concurrent jobs.
  if new.status in ('queued', 'drafting', 'waiting_for_facts', 'checking') then
    perform pg_advisory_xact_lock(hashtextextended(new.case_file_id::text, 0));
    if (select count(*) from document_generation_jobs
        where case_file_id = new.case_file_id
          and status in ('queued', 'drafting', 'waiting_for_facts', 'checking')
          and id <> new.id) >= 3 then
      raise exception 'per-case active document generation limit (3) reached';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists document_generation_active_limit on document_generation_jobs;
create trigger document_generation_active_limit
  before insert or update of status on document_generation_jobs
  for each row execute function enforce_document_generation_active_limit();

alter table document_generation_jobs enable row level security;
alter table document_generation_outcomes enable row level security;
-- No client policies: service-side scheduling and event endpoints own writes.
